"""empty message

Revision ID: 356b1cc844ae
Revises: 
Create Date: 2022-08-10 21:58:35.268057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356b1cc844ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
